backend:
  build: ./backend
  command: bash start.sh
  volumes:
    - ./backend:/app:rw
    - ~/.bash_history:/root/.bash_history
  ports:
    - "3000:3000"
    - "3035:3035"
  links:
    - postgres
    - redis
  environment:
    - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    - REDIS_URL=redis://redis:6379/

redis:
  image: redis
  ports:
    - "6379:6379"

postgres:
  image: postgres:9.6.8
  ports:
    - '5432:5432'
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=1234
  volumes:
    - ./.db_pg:/var/lib/postgresql/data
